packages:
  - name: webhooks
    actions:
      - name: paddle
        runtime: 'nodejs:18'
        limits:
          timeout: 5000
          memory: 512        
        environment:
          IP_DEV_1: "${IP_DEV_1}"
                
